#!/usr/bin/env python3
"""Build the built-in chambers into the app: chambers/*.txt -> a C file
defining chamber_builtins[] (main/chamber.h), in file-name order.

    embed_chambers.py <chambers dir> <output .c>
"""

import os
import sys


def c_escape(s):
    # ? too: "??/" is a trigraph in strict ISO C.
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("?", "\\?").replace("\n", "\\n")


def c_string(text):
    out = ['        "%s"' % c_escape(line) for line in text.splitlines(keepends=True)]
    return "\n".join(out) if out else '        ""'


def main():
    src, dst = sys.argv[1], sys.argv[2]
    names = sorted(n for n in os.listdir(src) if n.endswith(".txt"))
    parts = ["// Generated by tools/embed_chambers.py from chambers/*.txt. Do not edit.", '#include "chamber.h"', "",
             "chamber_builtin_t const chamber_builtins[] = {"]
    for n in names:
        with open(os.path.join(src, n), encoding="utf-8") as f:
            text = f.read()
        parts.append('    {"%s",\n%s},' % (c_escape(n[:-4]), c_string(text)))
    parts.append("};")
    parts.append("int const chamber_builtin_count = %d;" % len(names))
    data = "\n".join(parts) + "\n"
    os.makedirs(os.path.dirname(dst) or ".", exist_ok=True)
    # Unchanged output keeps its timestamp, so make does not rebuild for nothing.
    if os.path.exists(dst):
        with open(dst, encoding="utf-8") as f:
            if f.read() == data:
                return
    with open(dst, "w", encoding="utf-8") as f:
        f.write(data)


if __name__ == "__main__":
    main()
